### ISSUE TITLE
error message from empy native_filter could be more helpful

### ISSUE THREAD

**Issue by danielsf** [yymao/generic-catalog-reader#22]
This is not a huge priority, but if you pass the GCR a native_filter that returns an empty set, you get an error message that does not make it obvious what went wrong.  For example
```
>>> import GCRCatalogs
>>> from GCR import GCRQuery
>>> query = GCRQuery('healpix_pixel==-1')
>>> cat = GCRCatalogs.load_catalog('cosmoDC2_v1.0_image')
>>> cat.get_quantities('galaxy_id', native_filters=[query])['galaxy_id']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/lib/python3.6/site-packages/GCR/base.py", line 77, in get_quantities
    return {q: (np.concatenate(data_all[q]) if len(data_all[q]) > 1 else data_all[q][0]) for q in quantities}
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/lib/python3.6/site-packages/GCR/base.py", line 77, in <dictcomp>
    return {q: (np.concatenate(data_all[q]) if len(data_all[q]) > 1 else data_all[q][0]) for q in quantities}
IndexError: list index out of range
```
It might be nice for the GCR to tell you that your native filter returned nothing, so that you don't worry that something more fundamental has gone wrong.

Again: this is not a high priority.

**Comment by yymao** [comment]
Thanks for reporting this, @danielsf. This is actually a bug. The desired behavior is to return an empty array when `native_filters` return an empty set. 

This is now fixed in #23. I'll ask Heather to update the environment.
