### ISSUE TITLE
Provide method to query for quantity attributes

### ISSUE THREAD

**Issue by evevkovacs** [yymao/generic-catalog-reader#7]
@yyymao I think it would be useful to give users a way to query for more information about a quantity that the catalog creators have seen fit to provide. For example, in protoDC2, each quantity has a units attribute and will have a description attribute. I am think of a method such as 
gc.get_quantity_info(quantity_name, keyword='')
keyword could be '' (fetches all info), 'units' (fetches units) 'description' (fetches description).
If the catalog doesn't have anything, it returns 'Not available'. Catalog providers will implement this method in their reader to provide the information in whatever form they wish.
Then the list_quantities method could have an option return the list + all extra information. This would then be a nice online documentation for everything in the catalog.

**Comment by yymao** [comment]
Thanks @evevkovacs. This looks good and I've implement it in the base class in #8.
